post_upgrade() {
  if (( $(vercmp $2 1.16.0-3) < 0 )); then
    post_install
  fi
}

post_install() {
  cat <<MSG
>>> xorg-server has now the ability to run without root rights. To be
	able to use this features, install the package xorg-server-noroot.
	
$(tput setaf 3)>>> WARNING : $(tput sgr0)The file /etc/X11/Xwrapper.config
	need to be present on your system containing this following line :
	
	needs_root_rights = yes
	
	Please, see xorg.wrap man page for futher informations
MSG
}
